samples: config/samples.tsv

# The file extension. Usually one of fq.gz/fastq.gz/fq/fastq
ext: ".fq.gz"

# Common tags between the sample name given in samples.tsv and the extension
tags:
  r1: "_1"
  r2: "_2"

# Automatically add the output files to the git repo
autogit: "yes"

# The root argument tells you where the genome will be located
# on the local system. All other arguments are required for
# downloading
ref:
  build: GRCh38
  release: 101
  root: /hpcfs/users/a1018048/refs
  seqtype: primary_assembly
  species: homo_sapiens

# Given we only have 75nt reads, don't group during fastqc
fastqc:
  params: "--nogroup --noextract"

# Settings for Adapter Removal
trimming:
  adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
  adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
  maxns: 1
  minlength: 35
  minqual: 30
  extra: "--gzip --trimqualities"

# Settings for featureCounts
featureCounts:
  minQual: 0
  fracOverlap: 1
  strandedness: 0
  extra: "-p"
